logging:
  level:
     org:
       springframework:
       
         security: DEBUG
server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://peer1:8761/eureka
  datacenter: South_East_Asia
  environment: Dev
  instance: 
    hostname: peer2

management:
  security:
    enabled: false
#  server:
#    enableSelfPreservation: false
      