server:
  contextPath: /api/dev
  error:
    include-stacktrace: NEVER
  port: 8181
  
sample-client-2: 
  ribbon: 
    eureka: 
      enable: false
    ServerListRefreshInterval: 30000
    listOfServers: localhost:8082, localhost:8083, localhost:8084 

#    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true